"use server";

const teachings: Teaching[] = [
	{
		id: "1",
		date: "2025-11-09",
		title: "Romans 11:1-10",
		description: "",
		coverPhoto: "romans-11-series-11-2025.png",
		scripture: [
			{
				book: "Romans",
				chapter: 11,
				verses: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
				referenceType: "featured",
			},
			{
				book: "1 Kings",
				chapter: 19,
				verses: [
					"1",
					"2",
					"3",
					"4",
					"5",
					"6",
					"7",
					"8",
					"9",
					"10",
					"11",
					"12",
					"13",
					"14",
					"15",
					"16",
					"17",
					"18",
				],
				referenceType: "featured",
			},
			{ book: "Romans", chapter: 10, verses: ["31"], referenceType: "cross-referenced" },
			{ book: "Jeremiah", chapter: 31, verses: ["31"], referenceType: "cross-referenced" },
		],
		topics: ["remnant israel", "ethnic israel", "foreknowledge", "election", "predestination"],
		videoUrl: "https://www.youtube.com/embed/g5SxuRgVn9Y",
		notesUrl:
			"https://schtowkzjmfht9nx.public.blob.vercel-storage.com/teaching-notes/romans-11-1-10_notes.pdf",
		series: "Merge - Romans 11",
		nextInSeries: "2",
	},
	{
		id: "2",
		date: "2025-11-16",
		title: "Romans 11:11-22",
		description: "",
		coverPhoto: "romans-11-series-11-2025.png",
		scripture: [
			{
				book: "Romans",
				chapter: 11,
				verses: ["11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22"],
				referenceType: "featured",
			},
			{ book: "Romans", chapter: 9, verses: ["32", "33"], referenceType: "cross-referenced" },
			{
				book: "Ezekiel",
				chapter: 36,
				verses: ["22", "23", "24", "25", "26", "27", "28", "29", "30"],
				referenceType: "featured",
			},
			{ book: "Zechariah", chapter: 12, verses: ["10"], referenceType: "cross-referenced" },
			{ book: "Zechariah", chapter: 14, verses: ["9", "16"], referenceType: "cross-referenced" },
		],
		topics: [
			"israel",
			"future plan for israel",
			"fullness of the Gentiles",
			"israel's partial hardening",
			"millenial kingdom",
			"olive tree",
			"olive branches",
			"purpose for israel today",
		],
		videoUrl: "https://www.youtube.com/embed/1O9aeQa5rL8",
		notesUrl:
			"https://schtowkzjmfht9nx.public.blob.vercel-storage.com/teaching-notes/romans-11-11-22_notes.pdf",
		series: "Merge - Romans 11",
		nextInSeries: "3",
	},
	{
		id: "3",
		date: "2025-11-30",
		title: "Romans 11:23-36",
		description: "",
		coverPhoto: "romans-11-series-11-2025.png",
		scripture: [
			{
				book: "Romans",
				chapter: 11,
				verses: [
					"23",
					"24",
					"25",
					"26",
					"27",
					"28",
					"29",
					"30",
					"31",
					"32",
					"33",
					"34",
					"35",
					"36",
				],
				referenceType: "featured",
			},
			{ book: "Zechariah", chapter: 12, verses: ["10"], referenceType: "cross-referenced" },
			{
				book: "2 Samuel",
				chapter: 7,
				verses: ["10", "11", "12", "13"],
				referenceType: "cross-referenced",
			},
			{
				book: "Jeremiah",
				chapter: 31,
				verses: ["31", "32", "33", "34"],
				referenceType: "featured",
			},
			{
				book: "Ezekiel",
				chapter: 20,
				verses: ["33", "34", "35", "36", "37", "38"],
				referenceType: "featured",
			},
			{ book: "Revelation", chapter: 7, verses: ["2", "3", "4"], referenceType: "featured" },
		],
		topics: [
			"israel",
			"future plan for israel",
			"national israel",
			"the church",
			"grafted in",
			"partial hardening",
			"mercy",
			"glory of God",
		],
		videoUrl: "https://www.youtube.com/embed/EUdHZzqBRdU",
		notesUrl:
			"https://schtowkzjmfht9nx.public.blob.vercel-storage.com/teaching-notes/romans-11-23-36_notes.pdf",
		series: "Merge - Romans 11",
	},
	{
		id: "4",
		date: "2026-01-04",
		title: "What is Evangelism?",
		description: "How does the bible define 'evangelism'?",
		coverPhoto: "evangelism-workshop-01-2026.jpg",
		videoUrl: "https://www.youtube.com/embed/YOcG3FB8B1Q",
		notesUrl:
			"https://schtowkzjmfht9nx.public.blob.vercel-storage.com/teaching-notes/1-4-26_evangelism-workshop_what-is-evangelism_notes.pdf",
		series: "Evangelism Workshop",
		scripture: [
			{
				book: "Matthew",
				chapter: 28,
				verses: ["19"],
				referenceType: "featured",
			},
			{
				book: "2 Corinthians",
				chapter: 5,
				verses: ["17", "18", "19"],
				referenceType: "featured",
			},
		],
		topics: ["evangelism", "great commission", "reconciliation"],
		nextInSeries: "5",
	},
	{
		id: "5",
		date: "2026-01-11",
		title: "Motivations for Evangelism",
		description: "What does the Bible say should motivate us to evangelize?",
		coverPhoto: "evangelism-workshop-01-2026.jpg",
		videoUrl: "https://youtu.be/VIs1WgLUdAI",
		notesUrl:
			"https://schtowkzjmfht9nx.public.blob.vercel-storage.com/teaching-notes/1-11-26_why_evangelize_notes.pdf",
		series: "Evangelism Workshop",
		scripture: [
			{
				book: "Matthew",
				chapter: 28,
				verses: ["16", "17"],
				referenceType: "featured",
			},
			{
				book: "Revelation",
				chapter: 10,
				verses: ["8", "9", "10", "11"],
				referenceType: "featured",
			},
			{
				book: "Isaiah",
				chapter: 6,
				verses: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
				referenceType: "featured",
			},
			{ book: "John", chapter: 3, verses: ["16", "18"], referenceType: "cross-referenced" },
			{
				book: "2 Corinthians",
				chapter: 10,
				verses: ["20", "21"],
				referenceType: "cross-referenced",
			},
		],
		topics: [
			"evangelism",
			"great commission",
			"biblical motivations",
			"wrath of God",
			"grace of God",
		],
		nextInSeries: "8",
	},
	{
		id: "6",
		date: "2025-12-07",
		title: "The Promises of the Promised One",
		series: "The Promised One",
		description:
			"Biblical survey of Old Testament prophecies about the reason for the Christmas season.",
		coverPhoto: "12-2025_the-promised-one-cover.png",
		videoUrl: "https://www.youtube.com/embed/xzV6KVZ1nr8",
		notesUrl:
			"https://schtowkzjmfht9nx.public.blob.vercel-storage.com/teaching-notes/12-7-25-the_promised_one-bethlehem.pdf",
		scripture: [
			{ book: "Micah", chapter: 5, verses: ["2"], referenceType: "featured" },
			{
				book: "Luke",
				chapter: 2,
				verses: ["1", "2", "3", "4", "5", "6", "7"],
				referenceType: "cross-referenced",
			},
			{ book: "Numbers", chapter: 24, verses: ["17"], referenceType: "featured" },
			{ book: "Matthew", chapter: 2, verses: ["2"], referenceType: "cross-referenced" },
			{ book: "Hosea", chapter: 11, verses: ["1", "2"], referenceType: "featured" },
			{
				book: "Matthew",
				chapter: 2,
				verses: ["13", "14", "15"],
				referenceType: "cross-referenced",
			},
			{ book: "Isaiah", chapter: 7, verses: ["14"], referenceType: "featured" },
			{ book: "Matthew", chapter: 1, verses: ["22", "23"], referenceType: "cross-referenced" },
			{ book: "2 Samuel", chapter: 7, verses: ["12", "14"], referenceType: "featured" },
			{ book: "Matthew", chapter: 1, verses: ["1", "6"], referenceType: "cross-referenced" },
			{ book: "Malachi", chapter: 4, verses: ["5", "6"], referenceType: "featured" },
			{ book: "Matthew", chapter: 11, verses: ["14", "15"], referenceType: "cross-referenced" },
			{ book: "Isaiah", chapter: 53, verses: ["1", "2"], referenceType: "featured" },
			{ book: "Hebrews", chapter: 4, verses: ["15", "16"], referenceType: "cross-referenced" },
		],
		topics: [
			"christmas",
			"old testament prophecy",
			"jesus",
			"humanity of christ",
			"sovereignty of god",
		],
		nextInSeries: "7",
	},
	{
		id: "7",
		date: "2025-12-14",
		title: "Jesus is LORD",
		series: "The Promised One",
		description: "What does the Bible say about the promised one being the Lord?",
		coverPhoto: "12-2025_the-promised-one-cover.png",
		videoUrl: "https://www.youtube.com/embed/asZ45_5z8gw",
		notesUrl:
			"https://schtowkzjmfht9nx.public.blob.vercel-storage.com/teaching-notes/12-14-25-the_promised_one-lord.pdf",
		scripture: [
			{
				book: "2 Samuel",
				chapter: 7,
				verses: ["8", "9", "10", "11", "12", "13", "14", "15", "16"],
				referenceType: "featured",
			},
			{ book: "1 Kings", chapter: 4, verses: ["20", "21"], referenceType: "cross-referenced" },
			{
				book: "Hebrews",
				chapter: 4,
				verses: ["8", "9", "10", "11"],
				referenceType: "cross-referenced",
			},
			{ book: "Micah", chapter: 4, verses: ["1", "2", "3"], referenceType: "cross-referenced" },
			{ book: "Isaiah", chapter: 9, verses: ["6", "7"], referenceType: "cross-referenced" },
			{ book: "Zechariah", chapter: 6, verses: ["12", "13"], referenceType: "cross-referenced" },
			{ book: "Hebrews", chapter: 1, verses: ["5"], referenceType: "cross-referenced" },
		],
		topics: ["davidic covenant", "lord", "lordship", "king", "kingdom of god"],
	},
	{
		id: "8",
		date: "2026-01-18",
		title: "How to Evangelize (Romans Road)",
		description: "What is the Romans Road? How does it help us in our evangelism?",
		coverPhoto: "evangelism-workshop-01-2026.jpg",
		videoUrl: "https://www.youtube.com/embed/lkOby65E5lo",
		notesUrl:
			"https://schtowkzjmfht9nx.public.blob.vercel-storage.com/teaching-notes/1-18-26_how-to-evangelize_notes.pdf",
		series: "Evangelism Workshop",
		scripture: [
			{
				book: "Romans",
				chapter: 3,
				verses: ["23"],
				referenceType: "featured",
			},
			{ book: "Romans", chapter: 5, verses: ["8", "9"], referenceType: "featured" },
			{ book: "Romans", chapter: 6, verses: ["23"], referenceType: "featured" },
			{ book: "Romans", chapter: 8, verses: ["1"], referenceType: "featured" },
			{ book: "Romans", chapter: 10, verses: ["9"], referenceType: "featured" },
			{ book: "Romans", chapter: 3, verses: ["24", "26"], referenceType: "cross-referenced" },
			{ book: "Ephesians", chapter: 2, verses: ["8", "9"], referenceType: "cross-referenced" },
			{ book: "Luke", chapter: 12, verses: ["12"], referenceType: "cross-referenced" },
		],
		topics: ["evangelism", "gospel", "romans road", "salvation", "repentance", "eternal life"],
	},
	{
		id: "9",
		date: "2026-03-22",
		title: "What is the Bible?",
		description: "How does God's inspired Word transform us?",
		coverPhoto: "truth-that-leads-to-godliness.png",
		videoUrl: "https://www.youtube.com/embed/K5lQw3E_CZw",
		notesUrl:
			"https://schtowkzjmfht9nx.public.blob.vercel-storage.com/teaching-notes/3-22-25-2-timothy-3-16-17_notes.pdf",
		series: "Truth that Leads to Godliness",
		scripture: [
			{
				book: "2 Timothy",
				chapter: 3,
				verses: ["16", "17"],
				referenceType: "featured",
			},
			{
				book: "2 Peter",
				chapter: 1,
				verses: ["20", "21"],
				referenceType: "featured",
			},
			{ book: "Titus", chapter: 1, verses: ["1"], referenceType: "cross-referenced" },
			{ book: "Psalm", chapter: 119, verses: ["104", "105"], referenceType: "cross-referenced" },
			{
				book: "James",
				chapter: 1,
				verses: ["22", "23", "24", "25"],
				referenceType: "cross-referenced",
			},
			{ book: "2 Peter", chapter: 3, verses: ["16"], referenceType: "cross-referenced" },
		],
		topics: ["bible", "scripture", "inspiration", "sanctification", "inerrancy", "authority"],
	},
	{
		id: "10",
		date: "2026-04-07",
		title: "The Devastating Fall",
		description:
			"Where did all the evil in our world come from? Genesis 3 reveals sin's deceitful, appealing, and devastating nature — and the hope of redemption God offers through the promised offspring, Jesus Christ.",
		videoUrl: "https://www.youtube.com/embed/cEABdtcv4mg",
		coverPhoto: "genesis-3-4-7-2026.png",
		notesUrl:
			"https://schtowkzjmfht9nx.public.blob.vercel-storage.com/teaching-notes/4-7-26_genesis_3_the_devastating_fall.pdf",
		scripture: [
			{
				referenceType: "featured",
				book: "Genesis",
				chapter: 3,
				verses: [
					"1",
					"2",
					"3",
					"4",
					"5",
					"6",
					"7",
					"8",
					"9",
					"10",
					"11",
					"12",
					"13",
					"14",
					"15",
					"16",
					"17",
					"18",
					"19",
					"20",
					"21",
					"22",
					"23",
					"24",
				],
			},
			{ book: "1 John", chapter: 5, verses: ["19"], referenceType: "cross-referenced" },
			{ book: "Proverbs", chapter: 8, verses: ["13"], referenceType: "cross-referenced" },
			{ book: "Genesis", chapter: 8, verses: ["21"], referenceType: "cross-referenced" },
			{ book: "Jeremiah", chapter: 17, verses: ["9"], referenceType: "cross-referenced" },
			{ book: "Romans", chapter: 3, verses: ["23"], referenceType: "cross-referenced" },
			{ book: "Romans", chapter: 5, verses: ["12", "14"], referenceType: "cross-referenced" },
			{
				book: "1 Corinthians",
				chapter: 15,
				verses: ["48", "49"],
				referenceType: "cross-referenced",
			},
			{
				book: "Genesis",
				chapter: 1,
				verses: [
					"3",
					"4",
					"5",
					"6",
					"7",
					"8",
					"9",
					"10",
					"11",
					"12",
					"13",
					"14",
					"15",
					"16",
					"17",
					"18",
					"19",
					"20",
					"21",
					"22",
					"23",
					"24",
					"25",
					"26",
					"27",
					"28",
					"29",
					"30",
					"31",
				],
				referenceType: "cross-referenced",
			},
			{ book: "Genesis", chapter: 2, verses: ["7", "16", "17"], referenceType: "cross-referenced" },
			{ book: "Revelation", chapter: 12, verses: ["9"], referenceType: "cross-referenced" },
			{ book: "Revelation", chapter: 20, verses: ["2"], referenceType: "cross-referenced" },
			{ book: "Ezekiel", chapter: 28, verses: ["13"], referenceType: "cross-referenced" },
			{
				book: "Luke",
				chapter: 3,
				verses: [
					"23",
					"24",
					"25",
					"26",
					"27",
					"28",
					"29",
					"30",
					"31",
					"32",
					"33",
					"34",
					"35",
					"36",
					"37",
					"38",
				],
				referenceType: "cross-referenced",
			},
			{ book: "Luke", chapter: 22, verses: ["3"], referenceType: "cross-referenced" },
			{ book: "John", chapter: 13, verses: ["27"], referenceType: "cross-referenced" },
			{ book: "2 Corinthians", chapter: 11, verses: ["14"], referenceType: "cross-referenced" },
			{ book: "Romans", chapter: 1, verses: ["24", "25"], referenceType: "cross-referenced" },
			{ book: "1 John", chapter: 2, verses: ["16"], referenceType: "cross-referenced" },
			{ book: "Psalm", chapter: 16, verses: ["11"], referenceType: "cross-referenced" },
			{
				book: "Psalm",
				chapter: 139,
				verses: ["7", "8", "9", "10", "11", "12"],
				referenceType: "cross-referenced",
			},
			{ book: "Ephesians", chapter: 5, verses: ["23"], referenceType: "cross-referenced" },
			{ book: "1 Corinthians", chapter: 15, verses: ["55"], referenceType: "cross-referenced" },
			{ book: "Proverbs", chapter: 14, verses: ["12"], referenceType: "cross-referenced" },
			{ book: "Hebrews", chapter: 4, verses: ["16"], referenceType: "cross-referenced" },
			{ book: "1 Timothy", chapter: 2, verses: ["15"], referenceType: "cross-referenced" },
			{ book: "Colossians", chapter: 3, verses: ["23", "24"], referenceType: "cross-referenced" },
			{ book: "Romans", chapter: 16, verses: ["20"], referenceType: "cross-referenced" },
			{ book: "Titus", chapter: 2, verses: ["12"], referenceType: "cross-referenced" },
		],
		topics: [
			"sin",
			"evil",
			"fall",
			"satan",
			"temptation",
			"redemption",
			"gospel",
			"judgment",
			"original sin",
			"repentance",
			"shame",
			"adam and eve",
			"creation",
		],
	},
	{
		id: "11",
		date: "2026-04-13",
		title: "Psalm 19",
		description:
			"From the heavens above to the pages of Scripture, God has made Himself known. Psalm 19 reveals how creation declares His glory and how His perfect Word revives the soul, gives wisdom, and guards us from sin.",
		coverPhoto: "psalms-series-4-2026.png",
		videoUrl: "https://www.youtube.com/embed/7TmTG7sj7lA",
		notesUrl:
			"https://schtowkzjmfht9nx.public.blob.vercel-storage.com/teaching-notes/4-12-26_psalm_19.pdf",
		series: "Psalms - God's Heart Book",
		scripture: [
			{
				book: "Psalm",
				chapter: 19,
				verses: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14"],
				referenceType: "featured",
			},
			{ book: "Psalm", chapter: 23, verses: ["1", "2", "3"], referenceType: "cross-referenced" },
			{ book: "Psalm", chapter: 119, verses: ["105"], referenceType: "cross-referenced" },
			{ book: "Psalm", chapter: 1, verses: ["1", "2"], referenceType: "cross-referenced" },
			{ book: "Proverbs", chapter: 19, verses: ["21"], referenceType: "cross-referenced" },
			{ book: "Joshua", chapter: 1, verses: ["8"], referenceType: "cross-referenced" },
			{
				book: "John",
				chapter: 1,
				verses: ["1", "2", "3", "14"],
				referenceType: "cross-referenced",
			},
			{ book: "Colossians", chapter: 1, verses: ["16"], referenceType: "cross-referenced" },
			{
				book: "Romans",
				chapter: 1,
				verses: ["19", "20", "21", "22", "23"],
				referenceType: "cross-referenced",
			},
			{ book: "Romans", chapter: 10, verses: ["17"], referenceType: "cross-referenced" },
			{ book: "Ephesians", chapter: 1, verses: ["4", "5"], referenceType: "cross-referenced" },
			{ book: "Ephesians", chapter: 2, verses: ["10"], referenceType: "cross-referenced" },
		],
		topics: [
			"psalms",
			"creation",
			"general revelation",
			"special revelation",
			"scripture",
			"sufficiency of scripture",
			"meditation",
			"prayer",
			"sin",
			"worship",
		],
		isFeatured: true,
	},
];

export type ScriptureReference = {
	book: string;
	chapter: number;
	verses?: string[];
	/**
	 * 'featured' = primary scripture for the teaching (displayed to users)
	 * 'cross-referenced' = supplementary passages mentioned but not central to the teaching (hidden from display)
	 */
	referenceType: "featured" | "cross-referenced";
};

export type Teaching = {
	id: string;
	coverPhoto: string;
	date: string;
	title: string;
	description: string;
	videoUrl: string;
	notesUrl?: string;
	series?: string;
	scripture: ScriptureReference[];
	topics: string[];
	isFeatured?: boolean;
	nextInSeries?: string;
};

export async function getAllTeachings(): Promise<Teaching[]> {
	return teachings;
}
